### ISSUE TITLE
Garantir a execução do Duke no Travis

### ISSUE THREAD

**Issue by bispojr** [bispojr/grupo-acm#22]
![image](https://user-images.githubusercontent.com/4129178/46899175-7c2b5200-ce66-11e8-8215-92429f1cfab5.png)

No comando, `php artisan duke` o comando `duke` não está sendo reconhecido.

**Comment by dyeimys** [comment]
Vou avaliar, e em breve faço o envio da solução.

**Comment by bispojr** [comment]
Resolvido. Fiz a migração para o Laravel 5.7 e digitei o comando correto (`dusk` ao invés de `duke`... rss).
